name: splt_transformer
channels:
  - defaults
dependencies:
- python=3.7
- pip>=18.0
- conda>=4.5.9
- patchelf=0.9
- pip:
    - numpy==1.19.5
    - gym==0.18.0
    - matplotlib==3.3.4
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torch==1.10.2+cu113
    - typed-argument-parser
    - py-trees==0.8.3
    - git+https://github.com/rail-berkeley/d4rl@master#egg=d4rl
    - gitpython
    - pyproj==3.0.1
    - networkx==2.5.1
